package afriqueMed.domain.historyLog;

public enum ActionType {
    TICKET_CREATED,
    INTERVENTION_CREATED,
    TICKET_ACCEPTED,
    TICKET_STATUS_CHANGED,
    TICKET_ASSIGNED,
    TICKET_REFUSED,
    TICKET_SOLVED,
    INTERVENTION_STARTED,
    INTERVENTION_UPDATED,
    INTERVENTION_COMPLETED,
    INTERVENTION_DELETED,
    FILE_UPLOADED,
    COMMENT_ADDED,
    SIGNATURE_RECEIVED,
    TECHNICIAN_VACATION_STATUS_CHANGED,
    MANAGER_ACTION
}
