package afriqueMed.domain;

public enum Speciality {
    OPHTALMOLOGIE,
    CARDIOLOGIE,
    RADIOLOGIE,
    DERMATOLOGIE,
    NEUROLOGIE,
    ORTHOPEDIE,
    GYNECOLOGIE,
    UROLOGIE,
    PNEUMOLOGIE,
    PEDIATRIE,
    ONCOLOGIE,
    GASTROENTEROLOGIE,
    ENDOCRINOLOGIE,
    ANESTHESIOLOGIE,
    PATHOLOGIE,
    DENTISTERIE,
    OTORHINOLARYNGOLOGIE,
    NEPHROLOGIE,
    HEMATOLOGIE,
    IMMUNOLOGIE,
    REANIMATION,
    PHYSIOTHERAPIE,
    OTHERS
}
